#!/usr/bin/env tsx
// Modular file splitter - creates filesystem.ts and types.ts without complex code changes
import * as fs from 'fs';
import * as path from 'path';

const __dirname = path.dirname(new URL(import.meta.url).pathname);

console.log('📦 MODULE SPLITTER - Creating modular architecture\n');

// 1. Create filesystem.ts
if (!fs.existsSync('filesystem.ts')) {
  const fsCode = `// FileSystem - Sandboxed file operations
// Auto-generated by EvoAgent modularization
// DO NOT EDIT - Will be regenerated

import * as fs from 'fs';
import * as path from 'path';

function validatePath(filePath: string, allowedPaths: string[], blockedOps: string[]): { valid: boolean; reason?: string } {
  const fullPath = path.resolve(filePath);
  const inAllowed = allowedPaths.some(allowed => fullPath.startsWith(path.resolve(allowed)));
  if (!inAllowed) return { valid: false, reason: 'Access denied: outside allowed directories' };
  for (const blocked of blockedOps) {
    if (filePath.includes(blocked)) return { valid: false, reason: \`Blocked operation: \${blocked}\` };
  }
  return { valid: true };
}

export class FileSystem {
  private basePath: string;
  private allowedPaths: string[];
  private blockedOps: string[];

  constructor(basePath?: string, allowedPaths?: string[], blockedOps?: string[]) {
    this.basePath = basePath || '.';
    this.allowedPaths = allowedPaths || [this.basePath];
    this.blockedOps = blockedOps || ['/etc/', '/sys/', '/proc/'];
  }

  private validate(filePath: string): { valid: boolean; reason?: string } {
    return validatePath(path.resolve(this.basePath, filePath), this.allowedPaths, this.blockedOps);
  }

  readFile(filePath: string, encoding: string = 'utf-8'): string {
    const v = this.validate(filePath);
    if (!v.valid) throw new Error(\`FileSystem.readFile denied: \${v.reason}\`);
    return fs.readFileSync(path.resolve(this.basePath, filePath), { encoding });
  }

  writeFile(filePath: string, content: string): void {
    const v = this.validate(filePath);
    if (!v.valid) throw new Error(\`FileSystem.writeFile denied: \${v.reason}\`);
    const full = path.resolve(this.basePath, filePath);
    const dir = path.dirname(full);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(full, content, 'utf-8');
  }

  exists(filePath: string): boolean {
    try { const v = this.validate(filePath); return v.valid && fs.existsSync(path.resolve(this.basePath, filePath)); } catch { return false; }
  }

  listFiles(dirPath: string): string[] {
    const v = this.validate(dirPath);
    if (!v.valid) throw new Error(\`FileSystem.listFiles denied: \${v.reason}\`);
    const full = path.resolve(this.basePath, dirPath);
    return fs.existsSync(full) ? fs.readdirSync(full) : [];
  }

  appendFile(filePath: string, content: string): void {
    const v = this.validate(filePath);
    if (!v.valid) throw new Error(\`FileSystem.appendFile denied: \${v.reason}\`);
    const full = path.resolve(this.basePath, filePath);
    const dir = path.dirname(full);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(full, content, 'utf-8');
  }

  deleteFile(filePath: string): void {
    const v = this.validate(filePath);
    if (!v.valid) throw new Error(\`FileSystem.deleteFile denied: \${v.reason}\`);
    const full = path.resolve(this.basePath, filePath);
    if (fs.existsSync(full)) fs.unlinkSync(full);
  }

  mkdir(dirPath: string): void {
    const v = this.validate(dirPath);
    if (!v.valid) throw new Error(\`FileSystem.mkdir denied: \${v.reason}\`);
    fs.mkdirSync(path.resolve(this.basePath, dirPath), { recursive: true });
  }

  getStats(filePath: string): any {
    try { const v = this.validate(filePath); if (!v.valid) return null; return fs.statSync(path.resolve(this.basePath, filePath)); } catch { return null; }
  }

  readdirStats(dirPath: string): any[] {
    try { const v = this.validate(dirPath); if (!v.valid) return []; return fs.readdirSync(path.resolve(this.basePath, dirPath), { withFileTypes: true }).map(d => ({ name: d.name, isFile: d.isFile(), isDirectory: d.isDirectory() })); } catch { return []; }
  }
}
`;
  fs.writeFileSync('filesystem.ts', fsCode);
  console.log('✅ Created filesystem.ts');
} else {
  console.log('⏭️  filesystem.ts already exists');
}

// 2. Create types.ts
if (!fs.existsSync('types.ts')) {
  const typesCode = `// Shared type definitions for EvoAgent
// Auto-generated

export interface Message {
  id: string;
  from: string;
  to: string;
  content: any;
  timestamp: string;
  type: string;
  priority?: number;
  ttl?: number;
}

export interface Goal {
  id: string;
  description: string;
  priority: number;
  status: string;
  steps: string[];
  currentStep: number;
  createdAt: string;
  completedAt?: string;
  dependencies?: string[];
}

export interface EvolutionMetrics {
  iteration: number;
  level: number;
  capabilities: string[];
  performance: { memoryUsage: number; cpuTime: number; uptime: number; successRate?: number };
  codeQuality: { linesOfCode: number; complexity?: number };
  changes: string[];
  bugsFixed: number;
  timestamp: string;
  health: string;
}

export interface AgentConfig {
  maxIterations?: number;
  backupBeforeEvolve: boolean;
  logLevel: string;
  evolutionStrategy: string;
  enablePersistence: boolean;
  enableReplication: boolean;
  enablePlugins: boolean;
  enableOrchestration: boolean;
  enableSecurity: boolean;
  enableHealthChecks: boolean;
  maxChildren: number;
  memoryPath?: string;
  logPath?: string;
  resourceLimits?: { maxMemoryMB?: number; maxCpuMsPerIter?: number; maxOpenFiles?: number };
  security?: { requireAuth?: boolean; allowedPaths?: string[]; blockedOperations?: string[]; sandboxMode?: string };
}

export interface AgentState {
  level: number;
  capabilities: string[];
  memory: Map<string, any>;
  history: EvolutionMetrics[];
  config: AgentConfig;
  goals: any[];
  children: string[];
  messages: Message[];
  health: { status: string; lastCheck: string; consecutiveFailures: number; memoryPressure: number };
  stats: { totalIterations: number; totalMessagesSent: number; totalMessagesReceived: number; totalChildrenSpawned: number; totalGoalsCompleted: number; startTime: string };
  sandbox: { allowedPaths: string[]; blockedOperations: string[]; resourceLimits: { maxMemoryMB: number; maxCpuMsPerIter: number; maxOpenFiles: number } };
}

export interface EvolutionPlan {
  targetLevel: number;
  opportunity: string;
  priority: number;
  totalOpportunities: number;
  estimatedComplexity: number;
  requiresNewDependencies: boolean;
  changes: string[];
  riskLevel: string;
  rollbackPlan?: string[];
}
`;
  fs.writeFileSync('types.ts', typesCode);
  console.log('✅ Created types.ts');
} else {
  console.log('⏭️  types.ts already exists');
}

// 3. Create test-stubs.ts
if (!fs.existsSync('test-stubs.ts')) {
  const tests = `// Comprehensive test suite for EvoAgent
// Auto-generated - run with: npx jest test-stubs.ts or vitest

import { EvoAgent, EvolutionMetrics, Goal } from './evo.ts';

// Mock utilities
const mockNowISO = () => '2026-01-01T00:00:00.000Z';

describe('EvoAgent Core', () => {
  let agent: EvoAgent;

  beforeEach(() => {
    agent = new EvoAgent({
      maxIterations: 1,
      enableReplication: false,
      memoryPath: 'test-memory.json'
    });
  });

  afterEach(async () => {
    // Cleanup
  });

  test('initialization', () => {
    expect(agent.id).toBeDefined();
    expect(agent.state.level).toBeGreaterThan(0);
    expect(agent.state.capabilities).toContain('self-awareness');
    expect(agent.state.config).toBeDefined();
  });

  test('goal management', () => {
    const goal = agent.createGoal('Test goal', 1, ['Step 1', 'Step 2']);
    expect(goal.id).toBeDefined();
    expect(goal.status).toBe('pending');
    expect(goal.steps.length).toBe(2);

    const advanced = agent.advanceGoal(goal.id);
    expect(advanced).toBe(true);
    expect(goal.currentStep).toBe(1);
    expect(goal.status).toBe('in_progress');

    agent.advanceGoal(goal.id);
    expect(goal.status).toBe('completed');
    expect(goal.completedAt).toBeDefined();
  });

  test('goal dependencies', () => {
    const dep = agent.createGoal('Dependency', 1, ['Done']);
    agent.advanceGoal(dep.id);

    const main = agent.createGoal('Main', 1, ['Step'], [dep.id]);
    expect(main.dependencies).toContain(dep.id);

    // Should not advance if dep not complete (already complete, so ok)
    const result = agent.advanceGoal(main.id);
    expect(result).toBe(true);
  });

  test('messaging', () => {
    const messages = agent['state'].messages;
    agent.sendMessage('recipient-123', { data: 'test' }, 'request', 1, 10);
    expect(messages.length).toBe(1);
    expect(messages[0].to).toBe('recipient-123');
    expect(messages[0].type).toBe('request');
    expect(messages[0].ttl).toBe(10);

    // Test broadcast
    agent.state.children = ['child1', 'child2'];
    agent.broadcast({ broadcast: true });
    expect(messages.length).toBe(3); // +2 children
  });

  test('memory persistence', async () => {
    agent.state.memory.set('test-key', 'test-value');
    await agent['saveMemory']();

    // Verify file created and contains data
    const saved = JSON.parse(fs.readFileSync('memory.json', 'utf-8'));
    expect(saved.state.memory).toContainEqual(['test-key', 'test-value']);
  });

  test('health monitoring', () => {
    const health = agent['performHealthCheck']();
    expect(['healthy', 'degraded', 'unhealthy']).toContain(health.status);
    expect(health.memoryPressure).toBeGreaterThanOrEqual(0);
    expect(Array.isArray(health.issues)).toBe(true);
  });

  test('statistics tracking', () => {
    const initialIter = agent.state.stats.totalIterations;
    agent.sendMessage('test', 'data');
    expect(agent.state.stats.totalMessagesSent).toBe(1);
  });

  test('sandbox enforcement', () => {
    // Try to read outside allowed path should throw
    expect(() => agent.fs.readFile('/etc/passwd')).toThrow('denied');
  });
});

describe('FileSystem', () => {
  test('basic operations', () => {
    const fs = new (require('./evo.ts').FileSystem)('.');
    fs.writeFile('test.txt', 'hello');
    expect(fs.exists('test.txt')).toBe(true);
    const content = fs.readFile('test.txt');
    expect(content).toBe('hello');
    fs.deleteFile('test.txt');
    expect(fs.exists('test.txt')).toBe(false);
  });

  test('directory listing', () => {
    const fs = new (require('./evo.ts').FileSystem)('.');
    const files = fs.listFiles('.');
    expect(Array.isArray(files)).toBe(true);
  });
});

describe('Evolution Metrics', () => {
  test('metrics structure', () => {
    const metric: EvolutionMetrics = {
      iteration: 1,
      level: 10,
      capabilities: ['test'],
      performance: { memoryUsage: 10, cpuTime: 100, uptime: 1 },
      codeQuality: { linesOfCode: 100 },
      changes: [],
      bugsFixed: 0,
      timestamp: new Date().toISOString(),
      health: 'healthy'
    };
    expect(metric.iteration).toBe(1);
  });
});
`;
  fs.writeFileSync('test-stubs.ts', tests);
  console.log('✅ Created test-stubs.ts');
} else {
  console.log('⏭️  test-stubs.ts already exists');
}

console.log('\n🎉 Modular files created!');
console.log('Files:');
console.log('  - filesystem.ts (FileSystem class)');
console.log('  - types.ts (TypeScript interfaces)');
console.log('  - test-stubs.ts (Jest/Vitest test suite)');
console.log('\nTo use:');
console.log('  1. Review and manually integrate filesystem.ts into evo.ts');
console.log('  2. Import types from types.ts');
console.log('  3. Run tests: npx jest test-stubs.ts or npx vitest');
