// Consolidated dependencies - ONLY public API from index.d.ts

import type { Static, TSchema } from 'typebox';
export type { Static, TSchema };
export { Type } from 'typebox';

// ============================================================================
// @earendil-works/pi-agent-core
// ============================================================================
export type { AgentTool } from '@earendil-works/pi-agent-core';

// ============================================================================
// @earendil-works/pi-coding-agent (from dist/index.d.ts)
// ============================================================================

// Exports (values)
export {
  getAgentDir,
  getDocsPath,
  getExamplesPath,
  getPackageDir,
  getReadmePath,
  VERSION,
  AgentSession,
  parseSkillBlock,
  AuthStorage,
  FileAuthStorageBackend,
  InMemoryAuthStorageBackend,
  calculateContextTokens,
  collectEntriesForBranchSummary,
  compact,
  DEFAULT_COMPACTION_SETTINGS,
  estimateTokens,
  findCutPoint,
  findTurnStartIndex,
  generateBranchSummary,
  generateSummary,
  getLastAssistantUsage,
  prepareBranchEntries,
  serializeConversation,
  shouldCompact,
  createEventBus,
  EventBus,
  EventBusController,
  createExtensionRuntime,
  defineTool,
  discoverAndLoadExtensions,
  ExtensionRunner,
  isBashToolResult,
  isEditToolResult,
  isFindToolResult,
  isGrepToolResult,
  isLsToolResult,
  isReadToolResult,
  isToolCallEventType,
  isWriteToolResult,
  wrapRegisteredTool,
  wrapRegisteredTools,
  convertToLlm,
  ModelRegistry,
  DefaultPackageManager,
  DefaultResourceLoader,
  loadProjectContextFiles,
  createAgentSession,
  createAgentSessionFromServices,
  createAgentSessionRuntime,
  createAgentSessionServices,
  createBashTool,
  createCodingTools,
  createEditTool,
  createFindTool,
  createGrepTool,
  createLsTool,
  createReadOnlyTools,
  createReadTool,
  createWriteTool,
  SessionManager,
  buildSessionContext,
  CURRENT_SESSION_VERSION,
  getLatestCompactionEntry,
  parseSessionEntries,
  SettingsManager,
  formatSkillsForPrompt,
  loadSkills,
  loadSkillsFromDir,
  createBashToolDefinition,
  createEditToolDefinition,
  createFindToolDefinition,
  createGrepToolDefinition,
  createLsToolDefinition,
  createReadToolDefinition,
  createWriteToolDefinition,
  createLocalBashOperations,
  DEFAULT_MAX_BYTES,
  DEFAULT_MAX_LINES,
  formatSize,
  truncateHead,
  truncateLine,
  truncateTail,
  ProjectTrustStore,
  createSyntheticSourceInfo,
  main,
  InteractiveMode,
  runPrintMode,
  RpcClient,
  runRpcMode,
  ArminComponent,
  AssistantMessageComponent,
  BashExecutionComponent,
  BorderedLoader,
  BranchSummaryMessageComponent,
  CompactionSummaryMessageComponent,
  CustomEditor,
  CustomMessageComponent,
  DynamicBorder,
  ExtensionEditorComponent,
  ExtensionInputComponent,
  ExtensionSelectorComponent,
  FooterComponent,
  LoginDialogComponent,
  ModelSelectorComponent,
  OAuthSelectorComponent,
  SessionSelectorComponent,
  SettingsSelectorComponent,
  ShowImagesSelectorComponent,
  SkillInvocationMessageComponent,
  ThemeSelectorComponent,
  ThinkingSelectorComponent,
  ToolExecutionComponent,
  TreeSelectorComponent,
  UserMessageComponent,
  UserMessageSelectorComponent,
  rawKeyHint,
  keyHint,
  keyText,
  renderDiff,
  truncateToVisualLines,
  getLanguageFromPath,
  getMarkdownTheme,
  getSelectListTheme,
  getSettingsListTheme,
  highlightCode,
  initTheme,
  copyToClipboard,
  parseFrontmatter,
  stripFrontmatter,
  convertToPng,
  resizeImage,
  formatDimensionNote,
  getShellConfig,
} from '@earendil-works/pi-coding-agent';

// Export types ONLY from index.d.ts (not submodules directly)
export type {
  // Agent/Session
  AgentSessionConfig,
  AgentSessionEvent,
  AgentSessionEventListener,
  ModelCycleResult,
  ParsedSkillBlock,
  PromptOptions,
  SessionStats,
  AgentSessionRuntime,
  AgentSessionServices,
  CreateAgentSessionFromServicesOptions,
  CreateAgentSessionOptions,
  CreateAgentSessionResult,
  CreateAgentSessionRuntimeFactory,
  CreateAgentSessionRuntimeResult,
  CreateAgentSessionServicesOptions,
  PromptTemplate,

  // Session manager
  BranchSummaryEntry,
  CompactionEntry,
  CustomEntry,
  CustomMessageEntry,
  FileEntry,
  ModelChangeEntry,
  NewSessionOptions,
  SessionContext,
  SessionEntry,
  SessionEntryBase,
  SessionHeader,
  SessionInfo,
  SessionInfoEntry,
  SessionMessageEntry,
  ThinkingLevelChangeEntry,

  // Auth
  ApiKeyCredential,
  AuthCredential,
  AuthStatus,
  AuthStorageBackend,
  OAuthCredential,

  // Compaction
  BranchPreparation,
  BranchSummaryResult,
  CollectEntriesResult,
  CompactionResult,
  CutPointResult,
  FileOperations,
  GenerateBranchSummaryOptions,

  // Extensions
  Extension,
  ExtensionActions,
  ExtensionAPI,
  ExtensionCommandContext,
  ExtensionCommandContextActions,
  ExtensionContext,
  ExtensionContextActions,
  ExtensionError,
  ExtensionEvent,
  ExtensionFactory,
  ExtensionFlag,
  ExtensionHandler,
  ExtensionRuntime,
  ExtensionShortcut,
  ExtensionUIContext,
  ExtensionUIDialogOptions,
  ExtensionWidgetOptions,
  LoadExtensionsResult,
  MessageRenderer,
  MessageRenderOptions,
  ProjectTrustContext,
  ProjectTrustEvent,
  ProjectTrustEventDecision,
  ProjectTrustEventResult,
  ProjectTrustHandler,
  ProviderConfig,
  ProviderModelConfig,
  RegisteredCommand,
  RegisteredTool,
  ResolvedCommand,
  SlashCommandInfo,
  SlashCommandSource,
  SourceInfo,
  ToolDefinition,
  ToolExecutionMode,
  ToolInfo,
  ToolRenderResultOptions,

  // Handler types (from index.d.ts)
  AppKeybinding,
  AutocompleteProviderFactory,
  TerminalInputHandler,
  BeforeAgentStartEventResult,
  BuildSystemPromptOptions,
  CompactOptions,
  ExecOptions,
  ExecResult,
  InputEventResult,
  UserBashEventResult,

  // Events (from index.d.ts)
  AgentEndEvent,
  AgentStartEvent,
  AgentToolResult,
  AgentToolUpdateCallback,
  BeforeAgentStartEvent,
  BeforeProviderRequestEvent,
  BeforeProviderRequestEventResult,
  ContextEvent,
  ContextUsage,
  CustomToolCallEvent,
  EditToolCallEvent,
  InputEvent,
  InputSource,
  SessionBeforeCompactEvent,
  SessionBeforeForkEvent,
  SessionBeforeSwitchEvent,
  SessionBeforeTreeEvent,
  SessionCompactEvent,
  SessionShutdownEvent,
  SessionStartEvent,
  SessionTreeEvent,
  TurnEndEvent,
  TurnStartEvent,
  UserBashEvent,
  BashToolCallEvent,
  FindToolCallEvent,
  GrepToolCallEvent,
  LsToolCallEvent,
  ReadToolCallEvent,
  WriteToolCallEvent,
  ToolCallEvent,
  ToolCallEventResult,
  ToolResultEvent,

  // Tool types
  BashOperations,
  BashSpawnContext,
  BashSpawnHook,
  BashToolDetails,
  BashToolInput,
  BashToolOptions,
  EditOperations,
  EditToolDetails,
  EditToolInput,
  EditToolOptions,
  FindOperations,
  FindToolDetails,
  FindToolInput,
  FindToolOptions,
  GrepOperations,
  GrepToolDetails,
  GrepToolInput,
  GrepToolOptions,
  LsOperations,
  LsToolDetails,
  LsToolInput,
  LsToolOptions,
  ReadOperations,
  ReadToolDetails,
  ReadToolInput,
  ReadToolOptions,
  ToolsOptions,
  TruncationOptions,
  TruncationResult,
  WriteOperations,
  WriteToolInput,
  WriteToolOptions,

  // Package manager
  PackageManager,
  PathMetadata,
  ProgressCallback,
  ProgressEvent,
  ResolvedPaths,
  ResolvedResource,

  // Resource loader
  ResourceCollision,
  ResourceDiagnostic,
  ResourceLoader,

  // Settings
  CompactionSettings,
  DefaultProjectTrust,
  ImageSettings,
  PackageSource,
  RetrySettings,
  SettingsManagerCreateOptions,

  // Skills
  LoadSkillsFromDirOptions,
  LoadSkillsResult,
  Skill,
  SkillFrontmatter,

  // Trust
  ProjectTrustDecision,
  ProjectTrustStoreEntry,
  ProjectTrustUpdate,

  // Modes
  InteractiveModeOptions,
  ModelInfo,
  PrintModeOptions,
  RpcClientOptions,
  RpcCommand,
  RpcEventListener,
  RpcExtensionUIRequest,
  RpcExtensionUIResponse,
  RpcResponse,
  RpcSessionState,

  // UI components types
  RenderDiffOptions,
  SettingsCallbacks,
  SettingsConfig,
  ToolExecutionOptions,
  VisualTruncateResult,
  Theme,
  ThemeColor,
  ResizedImage,

  // Footer
  ReadonlyFooterDataProvider,

  // Main
  MainOptions,
} from '@earendil-works/pi-coding-agent';

// ============================================================================
// @earendil-works/pi-ai (from dist/index.d.ts)
// ============================================================================

export type {
  OpenAIResponsesOptions,
  OpenAICompletionsOptions,
  OpenAICodexResponsesOptions,
  OpenAICodexWebSocketDebugStats,
  AnthropicEffort,
  AnthropicOptions,
  AnthropicThinkingDisplay,
  AzureOpenAIResponsesOptions,
  BedrockOptions,
  BedrockThinkingDisplay,
  GoogleOptions,
  GoogleThinkingLevel,
  GoogleVertexOptions,
  MistralOptions,
  OAuthAuthInfo,
  OAuthCredentials,
  OAuthDeviceCodeInfo,
  OAuthLoginCallbacks,
  OAuthPrompt,
  OAuthProvider,
  OAuthSelectOption,
  OAuthSelectPrompt,
} from '@earendil-works/pi-ai';

// ============================================================================
// @earendil-works/pi-tui (from dist/index.d.ts)
// ============================================================================

export {
  TUI,
  Container,
  Component,
  Box,
  Text,
  Spacer,
  TruncatedText,
  CancellableLoader,
  Input,
  Editor,
  EditorOptions,
  EditorTheme,
  Markdown,
  MarkdownOptions,
  MarkdownTheme,
  Image,
  ImageOptions,
  ImageTheme,
  Loader,
  LoaderIndicatorOptions,
  SelectList,
  SelectListLayoutOptions,
  SelectListTheme,
  SelectListTruncatePrimaryContext,
  SettingsList,
  SettingsListTheme,
  FuzzyMatch,
  fuzzyFilter,
  fuzzyMatch,
  KeybindingsManager,
  getKeybindings,
  setKeybindings,
  TUI_KEYBINDINGS,
  Keybinding,
  KeybindingConflict,
  KeybindingDefinition,
  KeybindingDefinitions,
  Keybindings,
  KeybindingsConfig,
  Key,
  parseKey,
  matchesKey,
  setKittyProtocolActive,
  isKittyProtocolActive,
  decodeKittyPrintable,
  isKeyRelease,
  isKeyRepeat,
  Terminal,
  ProcessTerminal,
  StdinBuffer,
  StdinBufferOptions,
  StdinBufferEventMap,
  allocateImageId,
  deleteAllKittyImages,
  deleteKittyImage,
  detectCapabilities,
  encodeITerm2,
  encodeKitty,
  getCapabilities,
  getCellDimensions,
  getImageDimensions,
  getGifDimensions,
  getJpegDimensions,
  getPngDimensions,
  getWebpDimensions,
  imageFallback,
  renderImage,
  resetCapabilitiesCache,
  setCapabilities,
  setCellDimensions,
  hyperlink,
  calculateImageRows,
  truncateToWidth,
  visibleWidth,
  wrapTextWithAnsi,
} from '@earendil-works/pi-tui';

// Types from pi-tui index.d.ts
export type {
  AutocompleteItem,
  AutocompleteProvider,
  AutocompleteSuggestions,
  CombinedAutocompleteProvider,
  SlashCommand,
  OverlayAnchor,
  OverlayHandle,
  OverlayMargin,
  OverlayOptions,
  OverlayUnfocusOptions,
  SizeValue,
  Focusable,
  DefaultTextStyle,
  CellDimensions,
  ImageDimensions,
  ImageRenderOptions,
  TerminalCapabilities,
  ImageProtocol,
  EditorComponent,
  KeyEventType,
  KeyId,
} from '@earendil-works/pi-tui';
