// FileSystem - Sandboxed file operations
// Auto-generated by EvoAgent modularization
// DO NOT EDIT - Will be regenerated

import * as fs from 'fs';
import * as path from 'path';

function validatePath(filePath: string, allowedPaths: string[], blockedOps: string[]): { valid: boolean; reason?: string } {
  const fullPath = path.resolve(filePath);
  const inAllowed = allowedPaths.some(allowed => fullPath.startsWith(path.resolve(allowed)));
  if (!inAllowed) return { valid: false, reason: 'Access denied: outside allowed directories' };
  for (const blocked of blockedOps) {
    if (filePath.includes(blocked)) return { valid: false, reason: `Blocked operation: ${blocked}` };
  }
  return { valid: true };
}

export class FileSystem {
  private basePath: string;
  private allowedPaths: string[];
  private blockedOps: string[];

  constructor(basePath?: string, allowedPaths?: string[], blockedOps?: string[]) {
    this.basePath = basePath || '.';
    this.allowedPaths = allowedPaths || [this.basePath];
    this.blockedOps = blockedOps || ['/etc/', '/sys/', '/proc/'];
  }

  private validate(filePath: string): { valid: boolean; reason?: string } {
    return validatePath(path.resolve(this.basePath, filePath), this.allowedPaths, this.blockedOps);
  }

  readFile(filePath: string, encoding: BufferEncoding = 'utf-8'): string {
    const v = this.validate(filePath);
    if (!v.valid) throw new Error(`FileSystem.readFile denied: ${v.reason}`);
    return fs.readFileSync(path.resolve(this.basePath, filePath), { encoding } as any);
  }

  writeFile(filePath: string, content: string): void {
    const v = this.validate(filePath);
    if (!v.valid) throw new Error(`FileSystem.writeFile denied: ${v.reason}`);
    const full = path.resolve(this.basePath, filePath);
    const dir = path.dirname(full);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(full, content, 'utf-8');
  }

  exists(filePath: string): boolean {
    try { const v = this.validate(filePath); return v.valid && fs.existsSync(path.resolve(this.basePath, filePath)); } catch { return false; }
  }

  listFiles(dirPath: string): string[] {
    const v = this.validate(dirPath);
    if (!v.valid) throw new Error(`FileSystem.listFiles denied: ${v.reason}`);
    const full = path.resolve(this.basePath, dirPath);
    return fs.existsSync(full) ? fs.readdirSync(full) : [];
  }

  appendFile(filePath: string, content: string): void {
    const v = this.validate(filePath);
    if (!v.valid) throw new Error(`FileSystem.appendFile denied: ${v.reason}`);
    const full = path.resolve(this.basePath, filePath);
    const dir = path.dirname(full);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(full, content, 'utf-8');
  }

  deleteFile(filePath: string): void {
    const v = this.validate(filePath);
    if (!v.valid) throw new Error(`FileSystem.deleteFile denied: ${v.reason}`);
    const full = path.resolve(this.basePath, filePath);
    if (fs.existsSync(full)) fs.unlinkSync(full);
  }

  mkdir(dirPath: string): void {
    const v = this.validate(dirPath);
    if (!v.valid) throw new Error(`FileSystem.mkdir denied: ${v.reason}`);
    fs.mkdirSync(path.resolve(this.basePath, dirPath), { recursive: true });
  }

  getStats(filePath: string): any {
    try { const v = this.validate(filePath); if (!v.valid) return null; return fs.statSync(path.resolve(this.basePath, filePath)); } catch { return null; }
  }

  readdirStats(dirPath: string): any[] {
    try { const v = this.validate(dirPath); if (!v.valid) return []; return fs.readdirSync(path.resolve(this.basePath, dirPath), { withFileTypes: true }).map(d => ({ name: d.name, isFile: d.isFile(), isDirectory: d.isDirectory() })); } catch { return []; }
  }
}
