#!/usr/bin/env node
/**
 * Coverage Tool
 *
 * Displays code coverage statistics from the latest coverage run.
 * Reads coverage/coverage-summary.json generated by jest --coverage.
 */

import type { ExtensionAPI, ToolDefinition } from '@earendil-works/pi-coding-agent';
import { Text } from '@earendil-works/pi-tui';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

function createCoverageTool(): ToolDefinition<any, any> {
  return {
    name: 'coverage',
    label: 'Coverage',
    description: 'Display code coverage statistics from coverage/coverage-summary.json.',
    parameters: {},
    async execute(toolCallId, params, _signal, _onUpdate, ctx) {
      const cwd = ctx.cwd;
      const summaryPath = join(cwd, 'coverage', 'coverage-summary.json');

      try {
        const raw = await readFile(summaryPath, 'utf-8');
        const data = JSON.parse(raw);
        const total = data.total || data.totals || data;

        const getPct = (cov: any) => {
          const pct = typeof cov === 'number' ? cov : (cov?.pct || cov?.percent || 0);
          return Number(pct.toFixed?.(1) ?? pct);
        };

        const lines = [
          `📊 Coverage Summary`,
          `┌───────────────┬─────────────┐`,
          `│ Metrics       │ % Covered   │`,
          `├───────────────┼─────────────┤`,
          `│ Statements    │ ${getPct(total.statements || (total?.statements ?? 0))}%`.padEnd(14) + '│',
          `│ Branches      │ ${getPct(total.branches || (total?.branches ?? 0))}%`.padEnd(14) + '│',
          `│ Functions     │ ${getPct(total.functions || (total?.functions ?? 0))}%`.padEnd(14) + '│',
          `│ Lines         │ ${getPct(total.lines || (total?.lines ?? 0))}%`.padEnd(14) + '│',
          `└───────────────┴─────────────┘`,
        ];

        return {
          content: [{ type: 'text', text: lines.join('\n') }],
          details: { path: summaryPath, total: { statements: total.statements, branches: total.branches, functions: total.functions, lines: total.lines } },
          isError: false,
        };
      } catch (e: any) {
        if (e.code === 'ENOENT' || e.code === 'ENOTDIR') {
          return {
            content: [{ type: 'text', text: 'No coverage data found. Run tests with coverage first: `test { coverage: true }`' }],
            details: { error: 'coverage file missing' },
            isError: true,
          };
        }
        return {
          content: [{ type: 'text', text: `Error reading coverage: ${e.message}` }],
          details: { error: e.message },
          isError: true,
        };
      }
    },

    renderCall(args: any, theme: any) {
      const th = theme;
      const text = th.fg('toolTitle', th.bold('coverage')) + th.fg('muted', ' summary');
      return new Text(text, 0, 0);
    },

    renderResult(result: any, options: { expanded: boolean; isPartial: boolean }, theme: any) {
      const th = theme;
      if (options.isPartial) return new Text(th.fg('warning', 'Loading...'), 0, 0);
      if (result.isError) return new Text(th.fg('error', 'Error'), 0, 0);
      const details = result.details;
      if (!details) return new Text('', 0, 0);
      const pct = details.total?.statements?.pct ?? details.total?.statements ?? 0;
      const color = pct >= 80 ? 'success' : pct >= 60 ? 'warning' : 'error';
      return new Text(th.fg(color, `📈 ${pct.toFixed?.(1) ?? pct}%`), 0, 0);
    },
  };
}

export function registerCoverageTool(api: ExtensionAPI): void {
  api.registerTool(createCoverageTool());
}