#!/usr/bin/env node
/**
 * Coverage Leaders Tool
 *
 * Shows top and bottom coverage files to identify improvement targets.
 * Reads coverage/coverage-summary.json generated by jest --coverage.
 */

import type { ExtensionAPI, ToolDefinition } from '@earendil-works/pi-coding-agent';
import { Text } from '@earendil-works/pi-tui';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

interface FileCoverage {
  path: string;
  statements: { total: number; covered: number; pct: number };
  branches: { total: number; covered: number; pct: number };
  lines: { total: number; covered: number; pct: number };
  functions: { total: number; covered: number; pct: number };
}

function createCoverageLeadersTool(): ToolDefinition<any, any> {
  return {
    name: 'coverage-leaders',
    label: 'Coverage Leaders',
    description: 'Show top and bottom files by coverage to guide improvement efforts.',
    parameters: {},
    async execute(toolCallId, params, _signal, _onUpdate, ctx) {
      const cwd = ctx.cwd;
      const summaryPath = join(cwd, 'coverage', 'coverage-summary.json');

      try {
        const raw = await readFile(summaryPath, 'utf-8');
        const data = JSON.parse(raw);

        // Extract file coverages
        const files: FileCoverage[] = Object.entries(data)
          .filter(([key]) => key !== 'total' && key !== 'totals')
          .map(([path, cov]: [string, any]) => {
            const getMetric = (m: any) => ({
              total: m?.total || 0,
              covered: m?.covered || 0,
              pct: typeof m === 'number' ? m : (m?.pct || m?.percent || 0),
            });
            return {
              // Keep filename with extension; strip leading path up to src/
              path: path.replace(/^.*src[\\/]/, ''),
              statements: getMetric(cov?.statements || cov?.stmts || cov),
              branches: getMetric(cov?.branches || cov?.brhs || { total: 0, covered: 0, pct: 0 }),
              lines: getMetric(cov?.lines || cov),
              functions: getMetric(cov?.functions || cov?.funcs || { total: 0, covered: 0, pct: 0 }),
            };
          })
          .filter(f => f.statements.total > 0); // Only files with statements

        if (files.length === 0) {
          return {
            content: [{ type: 'text', text: 'No coverage data found for source files.' }],
            details: { count: 0 },
            isError: false,
          };
        }

        // Sort by statements coverage
        files.sort((a, b) => b.statements.pct - a.statements.pct);

        const topN = 5;
        const bottomN = 5;

        const pad = (s: string, n: number) => s.padEnd(n);
        const num = (n: number) => n.toFixed(1).padStart(6);

        const lines: string[] = [
          `🏆 Coverage Leaders (Top ${topN})`,
          `┌──────────────────────────────────────┬─────────────┐`,
          `│ File                                  │ Stmts %     │`,
          `├──────────────────────────────────────┼─────────────┤`,
          ...files.slice(0, topN).map(f =>
            `│ ${pad(f.path, 38)} │ ${num(f.statements.pct)}% │`
          ),
          `└──────────────────────────────────────┴─────────────┘`,
          '',
          `📉 Coverage Laggards (Bottom ${bottomN})`,
          `┌──────────────────────────────────────┬─────────────┐`,
          `│ File                                  │ Stmts %     │`,
          `├──────────────────────────────────────┼─────────────┤`,
          ...files.slice(-bottomN).reverse().map(f =>
            `│ ${pad(f.path, 38)} │ ${num(f.statements.pct)}% │`
          ),
          `└──────────────────────────────────────┴─────────────┘`,
          '',
          `Total files analyzed: ${files.length}`,
        ];

        return {
          content: [{ type: 'text', text: lines.join('\n') }],
          details: {
            totalFiles: files.length,
            top: files.slice(0, topN),
            bottom: files.slice(-bottomN),
          },
          isError: false,
        };
      } catch (e: any) {
        if (e.code === 'ENOENT' || e.code === 'ENOTDIR') {
          return {
            content: [{ type: 'text', text: 'No coverage data found. Run tests with coverage first: `test { coverage: true }`' }],
            details: { error: 'coverage file missing' },
            isError: true,
          };
        }
        return {
          content: [{ type: 'text', text: `Error reading coverage: ${e.message}` }],
          details: { error: e.message },
          isError: true,
        };
      }
    },

    renderCall(args: any, theme: any) {
      const th = theme;
      const text = th.fg('toolTitle', th.bold('coverage-leaders')) + th.fg('muted', ' leaders');
      return new Text(text, 0, 0);
    },

    renderResult(result: any, options: { expanded: boolean; isPartial: boolean }, theme: any) {
      const th = theme;
      if (options.isPartial) return new Text(th.fg('warning', 'Loading...'), 0, 0);
      if (result.isError) return new Text(th.fg('error', 'Error'), 0, 0);
      const details = result.details;
      if (!details || details.totalFiles === 0) return new Text(th.fg('muted', 'No data'), 0, 0);
      const topAvg = details.top?.[0]?.statements?.pct ?? 0;
      const color = topAvg >= 80 ? 'success' : topAvg >= 60 ? 'warning' : 'error';
      return new Text(th.fg(color, `📊 ${details.totalFiles} files`), 0, 0);
    },
  };
}

export function registerCoverageLeadersTool(api: ExtensionAPI): void {
  api.registerTool(createCoverageLeadersTool());
}
